const countriesData = [
  {code:"af",name:"Афганистан",region:"Азия",capital:"Кабул",location:"Южная Азия",government:"Исламский эмират",admin:"Унитарное",orgs:"ООН, ОИС, ШОС(наблюдатель)"},
  {code:"al",name:"Албания",region:"Европа",capital:"Тирана",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО"},
  {code:"dz",name:"Алжир",region:"Африка",capital:"Алжир",location:"Северная Африка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, ЛАГ, АС, ОПЕК"},
  {code:"ad",name:"Андорра",region:"Европа",capital:"Андорра-ла-Велья",location:"Южная Европа",government:"Парламентское княжество",admin:"Унитарное",orgs:"ООН, Совет Европы"},
  {code:"ao",name:"Ангола",region:"Африка",capital:"Луанда",location:"Южная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ОПЕК"},
  {code:"ag",name:"Антигуа и Барбуда",region:"Америка",capital:"Сент-Джонс",location:"Карибы",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"ar",name:"Аргентина",region:"Америка",capital:"Буэнос-Айрес",location:"Южная Америка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, G20, МЕРКОСУР"},
  {code:"am",name:"Армения",region:"Азия",capital:"Ереван",location:"Закавказье",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ОДКБ, ЕАЭС"},
  {code:"au",name:"Австралия",region:"Океания",capital:"Канберра",location:"Океания",government:"Парламентская монархия",admin:"Федерация",orgs:"ООН, G20, АТЭС, АНЗЮС"},
  {code:"at",name:"Австрия",region:"Европа",capital:"Вена",location:"Центральная Европа",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, ЕС, ОБСЕ"},
  {code:"az",name:"Азербайджан",region:"Азия",capital:"Баку",location:"Закавказье",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОИС, СНГ"},
  {code:"bs",name:"Багамы",region:"Америка",capital:"Нассау",location:"Карибы",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"bh",name:"Бахрейн",region:"Азия",capital:"Манама",location:"Персидский залив",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС"},
  {code:"bd",name:"Бангладеш",region:"Азия",capital:"Дакка",location:"Южная Азия",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ОИС, Содружество"},
  {code:"bb",name:"Барбадос",region:"Америка",capital:"Бриджтаун",location:"Карибы",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"by",name:"Беларусь",region:"Европа",capital:"Минск",location:"Восточная Европа",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОДКБ, ЕАЭС, СНГ"},
  {code:"be",name:"Бельгия",region:"Европа",capital:"Брюссель",location:"Западная Европа",government:"Парламентская монархия",admin:"Федерация",orgs:"ООН, НАТО, ЕС, Бенелюкс"},
  {code:"bz",name:"Белиз",region:"Америка",capital:"Бельмопан",location:"Центральная Америка",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество, ОАГ"},
  {code:"bj",name:"Бенин",region:"Африка",capital:"Порто-Ново",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"bt",name:"Бутан",region:"Азия",capital:"Тхимпху",location:"Южная Азия",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН"},
  {code:"bo",name:"Боливия",region:"Америка",capital:"Сукре",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"ba",name:"Босния и Герцеговина",region:"Европа",capital:"Сараево",location:"Южная Европа",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, Совет Европы"},
  {code:"bw",name:"Ботсвана",region:"Африка",capital:"Габороне",location:"Южная Африка",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"br",name:"Бразилия",region:"Америка",capital:"Бразилиа",location:"Южная Америка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, БРИКС, G20, МЕРКОСУР"},
  {code:"bn",name:"Бруней",region:"Азия",capital:"Бандар-Сери-Бегаван",location:"Юго-Восточная Азия",government:"Абсолютная монархия",admin:"Унитарное",orgs:"ООН, АСЕАН, ОИС"},
  {code:"bg",name:"Болгария",region:"Европа",capital:"София",location:"Юго-Восточная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"bf",name:"Буркина-Фасо",region:"Африка",capital:"Уагадугу",location:"Западная Африка",government:"Военная хунта",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"bi",name:"Бурунди",region:"Африка",capital:"Гитега",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"cv",name:"Кабо-Верде",region:"Африка",capital:"Прая",location:"Западная Африка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"kh",name:"Камбоджа",region:"Азия",capital:"Пномпень",location:"Юго-Восточная Азия",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, АСЕАН"},
  {code:"cm",name:"Камерун",region:"Африка",capital:"Яунде",location:"Центральная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Франкофония"},
  {code:"ca",name:"Канада",region:"Америка",capital:"Оттава",location:"Северная Америка",government:"Парламентская монархия",admin:"Федерация",orgs:"ООН, НАТО, G7, G20, АТЭС"},
  {code:"cf",name:"ЦАР",region:"Африка",capital:"Банги",location:"Центральная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"td",name:"Чад",region:"Африка",capital:"Нджамена",location:"Центральная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ОИС"},
  {code:"cl",name:"Чили",region:"Америка",capital:"Сантьяго",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ, АТЭС, ОЭСР"},
  {code:"cn",name:"Китай",region:"Азия",capital:"Пекин",location:"Восточная Азия",government:"Народная республика",admin:"Унитарное",orgs:"ООН, ШОС, БРИКС, АТЭС, ВТО"},
  {code:"co",name:"Колумбия",region:"Америка",capital:"Богота",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"km",name:"Коморы",region:"Африка",capital:"Морони",location:"Восточная Африка",government:"Федеративная республика",admin:"Федерация",orgs:"ООН, АС, ОИС, ЛАГ"},
  {code:"cg",name:"Конго",region:"Африка",capital:"Браззавиль",location:"Центральная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ОПЕК"},
  {code:"cd",name:"ДР Конго",region:"Африка",capital:"Киншаса",location:"Центральная Африка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"cr",name:"Коста-Рика",region:"Америка",capital:"Сан-Хосе",location:"Центральная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"hr",name:"Хорватия",region:"Европа",capital:"Загреб",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"cu",name:"Куба",region:"Америка",capital:"Гавана",location:"Карибы",government:"Социалистическая республика",admin:"Унитарное",orgs:"ООН"},
  {code:"cy",name:"Кипр",region:"Азия",capital:"Никосия",location:"Передняя Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ЕС, Содружество"},
  {code:"cz",name:"Чехия",region:"Европа",capital:"Прага",location:"Центральная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Вышеградская группа"},
  {code:"dk",name:"Дания",region:"Европа",capital:"Копенгаген",location:"Северная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"dj",name:"Джибути",region:"Африка",capital:"Джибути",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ЛАГ, ОИС"},
  {code:"dm",name:"Доминика",region:"Америка",capital:"Розо",location:"Карибы",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"do",name:"Доминикана",region:"Америка",capital:"Санто-Доминго",location:"Карибы",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"ec",name:"Эквадор",region:"Америка",capital:"Кито",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ, ОПЕК"},
  {code:"eg",name:"Египет",region:"Африка",capital:"Каир",location:"Северная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ЛАГ, АС, ОИС"},
  {code:"sv",name:"Сальвадор",region:"Америка",capital:"Сан-Сальвадор",location:"Центральная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"gq",name:"Экваториальная Гвинея",region:"Африка",capital:"Малабо",location:"Центральная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ОПЕК, Франкофония"},
  {code:"er",name:"Эритрея",region:"Африка",capital:"Асмэра",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"ee",name:"Эстония",region:"Европа",capital:"Таллин",location:"Северная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"sz",name:"Эсватини",region:"Африка",capital:"Мбабане",location:"Южная Африка",government:"Абсолютная монархия",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"et",name:"Эфиопия",region:"Африка",capital:"Аддис-Абеба",location:"Восточная Африка",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, АС"},
  {code:"fj",name:"Фиджи",region:"Океания",capital:"Сува",location:"Океания",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"fi",name:"Финляндия",region:"Европа",capital:"Хельсинки",location:"Северная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ЕС, НАТО"},
  {code:"fr",name:"Франция",region:"Европа",capital:"Париж",location:"Западная Европа",government:"Смешанная республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, G7, G20"},
  {code:"ga",name:"Габон",region:"Африка",capital:"Либревиль",location:"Центральная Африка",government:"Переходное правительство",admin:"Унитарное",orgs:"ООН, АС, ОПЕК, Франкофония"},
  {code:"gm",name:"Гамбия",region:"Африка",capital:"Банжул",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"ge",name:"Грузия",region:"Азия",capital:"Тбилиси",location:"Закавказье",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ГУАМ"},
  {code:"de",name:"Германия",region:"Европа",capital:"Берлин",location:"Центральная Европа",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, НАТО, ЕС, G7, G20"},
  {code:"gh",name:"Гана",region:"Африка",capital:"Аккра",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"gr",name:"Греция",region:"Европа",capital:"Афины",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"gd",name:"Гренада",region:"Америка",capital:"Сент-Джорджес",location:"Карибы",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"gt",name:"Гватемала",region:"Америка",capital:"Гватемала",location:"Центральная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"gn",name:"Гвинея",region:"Африка",capital:"Конакри",location:"Западная Африка",government:"Военная хунта",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"gw",name:"Гвинея-Бисау",region:"Африка",capital:"Бисау",location:"Западная Африка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, АС, Португалоязычные страны"},
  {code:"gy",name:"Гайана",region:"Америка",capital:"Джорджтаун",location:"Южная Америка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, Содружество, ОАГ"},
  {code:"ht",name:"Гаити",region:"Америка",capital:"Порт-о-Пренс",location:"Карибы",government:"Переходное правительство",admin:"Унитарное",orgs:"ООН, ОАГ, Франкофония"},
  {code:"hn",name:"Гондурас",region:"Америка",capital:"Тегусигальпа",location:"Центральная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"hu",name:"Венгрия",region:"Европа",capital:"Будапешт",location:"Центральная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Вышеградская группа"},
  {code:"is",name:"Исландия",region:"Европа",capital:"Рейкьявик",location:"Северная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ОЭСР"},
  {code:"in",name:"Индия",region:"Азия",capital:"Нью-Дели",location:"Южная Азия",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, БРИКС, ШОС, G20"},
  {code:"id",name:"Индонезия",region:"Азия",capital:"Джакарта",location:"Юго-Восточная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, G20, АСЕАН, АТЭС, ОИС"},
  {code:"ir",name:"Иран",region:"Азия",capital:"Тегеран",location:"Передняя Азия",government:"Исламская республика",admin:"Унитарное",orgs:"ООН, ОИС, ШОС, ОПЕК"},
  {code:"iq",name:"Ирак",region:"Азия",capital:"Багдад",location:"Передняя Азия",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, ЛАГ, ОИС, ОПЕК"},
  {code:"ie",name:"Ирландия",region:"Европа",capital:"Дублин",location:"Северная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ЕС"},
  {code:"il",name:"Израиль",region:"Азия",capital:"Иерусалим",location:"Передняя Азия",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ОЭСР"},
  {code:"it",name:"Италия",region:"Европа",capital:"Рим",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, G7, G20"},
  {code:"jm",name:"Ямайка",region:"Америка",capital:"Кингстон",location:"Карибы",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"jp",name:"Япония",region:"Азия",capital:"Токио",location:"Восточная Азия",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, G7, G20, АТЭС"},
  {code:"jo",name:"Иордания",region:"Азия",capital:"Амман",location:"Передняя Азия",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС"},
  {code:"kz",name:"Казахстан",region:"Азия",capital:"Астана",location:"Центральная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОДКБ, ЕАЭС, ШОС, ОБСЕ"},
  {code:"ke",name:"Кения",region:"Африка",capital:"Найроби",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"ki",name:"Кирибати",region:"Океания",capital:"Тарава",location:"Океания",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"kp",name:"КНДР",region:"Азия",capital:"Пхеньян",location:"Восточная Азия",government:"Социалистическая республика",admin:"Унитарное",orgs:"ООН"},
  {code:"kr",name:"Южная Корея",region:"Азия",capital:"Сеул",location:"Восточная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОЭСР, G20, АТЭС"},
  {code:"kw",name:"Кувейт",region:"Азия",capital:"Эль-Кувейт",location:"Персидский залив",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС, ОПЕК"},
  {code:"kg",name:"Кыргызстан",region:"Азия",capital:"Бишкек",location:"Центральная Азия",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ОДКБ, ЕАЭС, ШОС"},
  {code:"la",name:"Лаос",region:"Азия",capital:"Вьентьян",location:"Юго-Восточная Азия",government:"Социалистическая республика",admin:"Унитарное",orgs:"ООН, АСЕАН"},
  {code:"lv",name:"Латвия",region:"Европа",capital:"Рига",location:"Северная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"lb",name:"Ливан",region:"Азия",capital:"Бейрут",location:"Передняя Азия",government:"Конфессиональная республика",admin:"Унитарное",orgs:"ООН, ЛАГ, Франкофония"},
  {code:"ls",name:"Лесото",region:"Африка",capital:"Масеру",location:"Южная Африка",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"lr",name:"Либерия",region:"Африка",capital:"Монровия",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"ly",name:"Ливия",region:"Африка",capital:"Триполи",location:"Северная Африка",government:"Переходное правительство",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС, ОПЕК"},
  {code:"li",name:"Лихтенштейн",region:"Европа",capital:"Вадуц",location:"Центральная Европа",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, ЕАСТ"},
  {code:"lt",name:"Литва",region:"Европа",capital:"Вильнюс",location:"Северная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"lu",name:"Люксембург",region:"Европа",capital:"Люксембург",location:"Западная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Бенелюкс"},
  {code:"mg",name:"Мадагаскар",region:"Африка",capital:"Антананариву",location:"Восточная Африка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, АС, Франкофония"},
  {code:"mw",name:"Малави",region:"Африка",capital:"Лилонгве",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"my",name:"Малайзия",region:"Азия",capital:"Куала-Лумпур",location:"Юго-Восточная Азия",government:"Парламентская монархия",admin:"Федерация",orgs:"ООН, АСЕАН, ОИС, АТЭС, Содружество"},
  {code:"mv",name:"Мальдивы",region:"Азия",capital:"Мале",location:"Южная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОИС, Содружество"},
  {code:"ml",name:"Мали",region:"Африка",capital:"Бамако",location:"Западная Африка",government:"Военная хунта",admin:"Унитарное",orgs:"ООН, АС, ОИС"},
  {code:"mt",name:"Мальта",region:"Европа",capital:"Валлетта",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ЕС, Содружество"},
  {code:"mh",name:"Маршалловы Острова",region:"Океания",capital:"Маджуро",location:"Океания",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН"},
  {code:"mr",name:"Мавритания",region:"Африка",capital:"Нуакшот",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ЛАГ, ОИС"},
  {code:"mu",name:"Маврикий",region:"Африка",capital:"Порт-Луи",location:"Восточная Африка",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество, Франкофония"},
  {code:"mx",name:"Мексика",region:"Америка",capital:"Мехико",location:"Северная Америка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, G20, АТЭС, ОАГ"},
  {code:"fm",name:"Микронезия",region:"Океания",capital:"Паликир",location:"Океания",government:"Парламентская республика",admin:"Федерация",orgs:"ООН"},
  {code:"md",name:"Молдова",region:"Европа",capital:"Кишинёв",location:"Восточная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ГУАМ"},
  {code:"mc",name:"Монако",region:"Европа",capital:"Монако",location:"Западная Европа",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, Франкофония"},
  {code:"mn",name:"Монголия",region:"Азия",capital:"Улан-Батор",location:"Восточная Азия",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ШОС(наблюдатель)"},
  {code:"me",name:"Черногория",region:"Европа",capital:"Подгорица",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО"},
  {code:"ma",name:"Марокко",region:"Африка",capital:"Рабат",location:"Северная Африка",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, АС"},
  {code:"mz",name:"Мозамбик",region:"Африка",capital:"Мапуту",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество, Португалоязычные"},
  {code:"mm",name:"Мьянма",region:"Азия",capital:"Нейпьидо",location:"Юго-Восточная Азия",government:"Военная хунта",admin:"Унитарное",orgs:"ООН, АСЕАН"},
  {code:"na",name:"Намибия",region:"Африка",capital:"Виндхук",location:"Южная Африка",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"nr",name:"Науру",region:"Океания",capital:"Ярен",location:"Океания",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"np",name:"Непал",region:"Азия",capital:"Катманду",location:"Южная Азия",government:"Парламентская республика",admin:"Федерация",orgs:"ООН"},
  {code:"nl",name:"Нидерланды",region:"Европа",capital:"Амстердам",location:"Западная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Бенелюкс"},
  {code:"nz",name:"Новая Зеландия",region:"Океания",capital:"Веллингтон",location:"Океания",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, АНЗЮС, ОЭСР, Содружество"},
  {code:"ni",name:"Никарагуа",region:"Америка",capital:"Манагуа",location:"Центральная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"ne",name:"Нигер",region:"Африка",capital:"Ниамей",location:"Западная Африка",government:"Военная хунта",admin:"Унитарное",orgs:"ООН, АС, ОИС, Франкофония"},
  {code:"ng",name:"Нигерия",region:"Африка",capital:"Абуджа",location:"Западная Африка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, АС, ОИС, ОПЕК, Содружество"},
  {code:"mk",name:"Северная Македония",region:"Европа",capital:"Скопье",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО"},
  {code:"no",name:"Норвегия",region:"Европа",capital:"Осло",location:"Северная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, НАТО, ОЭСР"},
  {code:"om",name:"Оман",region:"Азия",capital:"Маскат",location:"Персидский залив",government:"Абсолютная монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС"},
  {code:"pk",name:"Пакистан",region:"Азия",capital:"Исламабад",location:"Южная Азия",government:"Парламентская республика",admin:"Федерация",orgs:"ООН, ОИС, ШОС, Содружество"},
  {code:"pw",name:"Палау",region:"Океания",capital:"Нгерулмуд",location:"Океания",government:"Президентская республика",admin:"Унитарное",orgs:"ООН"},
  {code:"ps",name:"Палестина",region:"Азия",capital:"Рамалла",location:"Передняя Азия",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН(наблюдатель), ЛАГ, ОИС"},
  {code:"pa",name:"Панама",region:"Америка",capital:"Панама",location:"Центральная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"pg",name:"Папуа — Новая Гвинея",region:"Океания",capital:"Порт-Морсби",location:"Океания",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество, АТЭС"},
  {code:"py",name:"Парагвай",region:"Америка",capital:"Асунсьон",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ, МЕРКОСУР"},
  {code:"pe",name:"Перу",region:"Америка",capital:"Лима",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ, АТЭС"},
  {code:"ph",name:"Филиппины",region:"Азия",capital:"Манила",location:"Юго-Восточная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АСЕАН, АТЭС"},
  {code:"pl",name:"Польша",region:"Европа",capital:"Варшава",location:"Центральная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Вышеградская группа"},
  {code:"pt",name:"Португалия",region:"Европа",capital:"Лиссабон",location:"Юго-Западная Европа",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Португалоязычные"},
  {code:"qa",name:"Катар",region:"Азия",capital:"Доха",location:"Персидский залив",government:"Абсолютная монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС, ОПЕК"},
  {code:"ro",name:"Румыния",region:"Европа",capital:"Бухарест",location:"Юго-Восточная Европа",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"ru",name:"Российская Федерация",region:"Европа",capital:"Москва",location:"Восточная Европа и Северная Азия",government:"Смешанная республика",admin:"Федерация",orgs:"ООН, ОДКБ, ЕАЭС, ШОС, БРИКС, СНГ"},
  {code:"rw",name:"Руанда",region:"Африка",capital:"Кигали",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Франкофония, Содружество"},
  {code:"kn",name:"Сент-Китс и Невис",region:"Америка",capital:"Бастер",location:"Карибы",government:"Парламентская монархия",admin:"Федерация",orgs:"ООН, Содружество"},
  {code:"lc",name:"Сент-Люсия",region:"Америка",capital:"Кастри",location:"Карибы",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество, Франкофония"},
  {code:"vc",name:"Сент-Винсент и Гренадины",region:"Америка",capital:"Кингстаун",location:"Карибы",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"ws",name:"Самоа",region:"Океания",capital:"Апия",location:"Океания",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"sm",name:"Сан-Марино",region:"Европа",capital:"Сан-Марино",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Совет Европы"},
  {code:"st",name:"Сан-Томе и Принсипи",region:"Африка",capital:"Сан-Томе",location:"Центральная Африка",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, АС, Португалоязычные"},
  {code:"sa",name:"Саудовская Аравия",region:"Азия",capital:"Эр-Рияд",location:"Передняя Азия",government:"Абсолютная монархия",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС, ОПЕК, G20"},
  {code:"sn",name:"Сенегал",region:"Африка",capital:"Дакар",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, ОИС, Франкофония"},
  {code:"rs",name:"Сербия",region:"Европа",capital:"Белград",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, ОБСЕ"},
  {code:"sc",name:"Сейшельские Острова",region:"Африка",capital:"Виктория",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество, Франкофония"},
  {code:"sl",name:"Сьерра-Леоне",region:"Африка",capital:"Фритаун",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"sg",name:"Сингапур",region:"Азия",capital:"Сингапур",location:"Юго-Восточная Азия",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, АСЕАН, Содружество, АТЭС"},
  {code:"sk",name:"Словакия",region:"Европа",capital:"Братислава",location:"Центральная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, Вышеградская группа"},
  {code:"si",name:"Словения",region:"Европа",capital:"Любляна",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, НАТО, ЕС"},
  {code:"sb",name:"Соломоновы Острова",region:"Океания",capital:"Хониара",location:"Океания",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"so",name:"Сомали",region:"Африка",capital:"Могадишо",location:"Восточная Африка",government:"Федеративная республика",admin:"Федерация",orgs:"ООН, АС, ЛАГ, ОИС"},
  {code:"za",name:"ЮАР",region:"Африка",capital:"Претория",location:"Южная Африка",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, БРИКС, G20, АС, Содружество"},
  {code:"ss",name:"Южный Судан",region:"Африка",capital:"Джуба",location:"Восточная Африка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, АС"},
  {code:"es",name:"Испания",region:"Европа",capital:"Мадрид",location:"Юго-Западная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, НАТО, ЕС, ОЭСР"},
  {code:"lk",name:"Шри-Ланка",region:"Азия",capital:"Шри-Джаяварденепура-Котте",location:"Южная Азия",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"sd",name:"Судан",region:"Африка",capital:"Хартум",location:"Северо-Восточная Африка",government:"Военный совет",admin:"Унитарное",orgs:"ООН, ЛАГ, АС, ОИС"},
  {code:"sr",name:"Суринам",region:"Америка",capital:"Парамарибо",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ"},
  {code:"se",name:"Швеция",region:"Европа",capital:"Стокгольм",location:"Северная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, ЕС, ОЭСР"},
  {code:"ch",name:"Швейцария",region:"Европа",capital:"Берн",location:"Центральная Европа",government:"Директориальная республика",admin:"Федерация",orgs:"ООН, ОЭСР, ОБСЕ, ВТО, ЕАСТ"},
  {code:"sy",name:"Сирия",region:"Азия",capital:"Дамаск",location:"Передняя Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ЛАГ"},
  {code:"tw",name:"Тайвань",region:"Азия",capital:"Тайбэй",location:"Восточная Азия",government:"Полупрезидентская республика",admin:"Унитарное",orgs:"ВТО, АТЭС(как Тайбэй)"},
  {code:"tj",name:"Таджикистан",region:"Азия",capital:"Душанбе",location:"Центральная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОДКБ, ШОС"},
  {code:"tz",name:"Танзания",region:"Африка",capital:"Додома",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"th",name:"Таиланд",region:"Азия",capital:"Бангкок",location:"Юго-Восточная Азия",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, АСЕАН, АТЭС"},
  {code:"tl",name:"Восточный Тимор",region:"Азия",capital:"Дили",location:"Юго-Восточная Азия",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, АСЕАН(наблюдатель), Португалоязычные"},
  {code:"tg",name:"Того",region:"Африка",capital:"Ломе",location:"Западная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Франкофония"},
  {code:"to",name:"Тонга",region:"Океания",capital:"Нукуалофа",location:"Океания",government:"Конституционная монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"tt",name:"Тринидад и Тобаго",region:"Америка",capital:"Порт-оф-Спейн",location:"Карибы",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Содружество, ОАГ"},
  {code:"tn",name:"Тунис",region:"Африка",capital:"Тунис",location:"Северная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ЛАГ, АС, Франкофония"},
  {code:"tr",name:"Турция",region:"Азия",capital:"Анкара",location:"Передняя Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, НАТО, G20, ОИС"},
  {code:"tm",name:"Туркменистан",region:"Азия",capital:"Ашхабад",location:"Центральная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОИС, СНГ(ассоциированный)"},
  {code:"tv",name:"Тувалу",region:"Океания",capital:"Фунафути",location:"Океания",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, Содружество"},
  {code:"ug",name:"Уганда",region:"Африка",capital:"Кампала",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"ua",name:"Украина",region:"Европа",capital:"Киев",location:"Восточная Европа",government:"Парламентско-президентская республика",admin:"Унитарное",orgs:"ООН, Совет Европы, ОБСЕ, ГУАМ"},
  {code:"ae",name:"ОАЭ",region:"Азия",capital:"Абу-Даби",location:"Персидский залив",government:"Федеративная монархия",admin:"Федерация",orgs:"ООН, ЛАГ, ОИС, ОПЕК"},
  {code:"gb",name:"Великобритания",region:"Европа",capital:"Лондон",location:"Северо-Западная Европа",government:"Парламентская монархия",admin:"Унитарное",orgs:"ООН, НАТО, G7, G20, Содружество"},
  {code:"us",name:"США",region:"Америка",capital:"Вашингтон",location:"Северная Америка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, НАТО, G7, G20, АТЭС, ОАГ"},
  {code:"uy",name:"Уругвай",region:"Америка",capital:"Монтевидео",location:"Южная Америка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ОАГ, МЕРКОСУР"},
  {code:"uz",name:"Узбекистан",region:"Азия",capital:"Ташкент",location:"Центральная Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ШОС, СНГ, ОИС"},
  {code:"vu",name:"Вануату",region:"Океания",capital:"Порт-Вила",location:"Океания",government:"Парламентская республика",admin:"Унитарное",orgs:"ООН, Франкофония, Содружество"},
  {code:"va",name:"Ватикан",region:"Европа",capital:"Ватикан",location:"Южная Европа",government:"Абсолютная теократическая монархия",admin:"Унитарное",orgs:"ООН(наблюдатель)"},
  {code:"ve",name:"Венесуэла",region:"Америка",capital:"Каракас",location:"Южная Америка",government:"Президентская республика",admin:"Федерация",orgs:"ООН, ОАГ, ОПЕК"},
  {code:"vn",name:"Вьетнам",region:"Азия",capital:"Ханой",location:"Юго-Восточная Азия",government:"Социалистическая республика",admin:"Унитарное",orgs:"ООН, АСЕАН, АТЭС"},
  {code:"ye",name:"Йемен",region:"Азия",capital:"Сана",location:"Передняя Азия",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, ЛАГ, ОИС"},
  {code:"zm",name:"Замбия",region:"Африка",capital:"Лусака",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС, Содружество"},
  {code:"zw",name:"Зимбабве",region:"Африка",capital:"Хараре",location:"Восточная Африка",government:"Президентская республика",admin:"Унитарное",orgs:"ООН, АС"},
  {code:"xk",name:"Косово",region:"Европа",capital:"Приштина",location:"Южная Европа",government:"Парламентская республика",admin:"Унитарное",orgs:"МВФ, Всемирный банк"}
];